Address PR comments

diff --git a/bin/list-incomplete-messages b/bin/list-incomplete-messages
--- a/bin/list-incomplete-messages
+++ b/bin/list-incomplete-messages
@@ -32,24 +32,24 @@ function get_messages() {
 
 function diff_messages() {
   if [[ ! -z "${2}" ]]; then
-    echo "Missing translations in $3:"
+    out::error "Missing translations in ${3}:"
 
     local difference="$(diff -b --strip-trailing-cr <(echo "$1") <(echo "$2"))"
     echo "${difference}" \
       | grep "<" \
       | grep -o "[^<][a-zA-Z.]*" \
-      | sed "s/^/    /"
+      | sed "s/^/    /" >&2
 
     local extra=$(echo "${difference}" \
       | grep ">" \
       | grep -o "[^>]*")
 
     if [[ ! -z "${extra}" ]]; then
-      echo "  Something weird is going on with these messages:"
-      echo "${extra}" | sed "s/^/    /"
+      out::error "  Something weird is going on with these messages:"
+      out::error "${extra}" | sed "s/^/    /"
     fi
   else
-    echo "There are no translations in ${3}"
+    out::error "There are no translations in ${3}"
   fi
 }
 
@@ -57,18 +57,17 @@ readonly MESSAGES_FILE="universal-application-tool-0.0.1/conf/messages"
 readonly MESSAGES="$(get_messages ${MESSAGES_FILE})"
 
 if [ $# -eq 1 ]; then
-  readonly TRANSLATION="$1"
-  readonly TRANSLATED_MESSAGES_FILE="${MESSAGES_FILE}.${TRANSLATION}"
+  readonly LANGUAGE="$1"
+  readonly TRANSLATED_MESSAGES_FILE="${MESSAGES_FILE}.${LANGUAGE}"
 
   if [ -f "${TRANSLATED_MESSAGES_FILE}" ]; then
     TRANSLATED_MESSAGES="$(get_messages ${TRANSLATED_MESSAGES_FILE})"
     diff_messages "$MESSAGES" "$TRANSLATED_MESSAGES" "$TRANSLATED_MESSAGES_FILE"
   else
-    echo "File ${TRANSLATED_MESSAGES_FILE} does not exist."
+    out::error "File ${TRANSLATED_MESSAGES_FILE} does not exist."
   fi
 else
-  for TRANSLATED_MESSAGES_FILE in ${MESSAGES_FILE}.*
-  do
+  for TRANSLATED_MESSAGES_FILE in ${MESSAGES_FILE}.*; do
     TRANSLATED_MESSAGES="$(get_messages ${TRANSLATED_MESSAGES_FILE})"
     diff_messages "$MESSAGES" "$TRANSLATED_MESSAGES" "$TRANSLATED_MESSAGES_FILE"
   done
