move common deploy logic into cloud/azure/bin/deploy

diff --git a/cloud/azure/bin/deploy b/cloud/azure/bin/deploy
--- a/cloud/azure/bin/deploy
+++ b/cloud/azure/bin/deploy
@@ -1,7 +1,27 @@
 #! /usr/bin/env bash
 
-KEEP_ORIGINAL_PWD=true source "${PROJECT_BASE_DIR}/bin/lib.sh"
-source "${PROJECT_BASE_DIR}/cloud/shared/bin/lib.sh"
-source "${PROJECT_BASE_DIR}/cloud/azure/bin/lib.sh"
+source "cloud/shared/bin/lib/health.sh"
+source "cloud/azure/bin/lib.sh"
+
+set -e
 
 # TODO: implement actual Azure deployment logic
+
+readonly APP_NAME="$(azure::get_app_name "${AZURE_RESOURCE_GROUP}")"
+readonly CANARY_URL="$(azure::get_canary_url "${AZURE_RESOURCE_GROUP}" "${APP_NAME}")"
+
+azure::set_new_container_tag ${AZURE_RESOURCE_GROUP} ${APP_NAME} ${DOCKER_TAG}
+
+if health::wait_for_success "${CANARY_URL}/loginForm"; 
+then
+    echo "New container successfully started in canary slot"
+else
+    # TODO: log failure + exit early. don't do the swap
+    exit 1
+fi
+
+echo "Swapping deployment slot 'canary' into production. This may take up to 10 minutes."
+azure::swap_deployment_slot "${AZURE_RESOURCE_GROUP}" "${APP_NAME}"
+
+echo "Success! The new application version is up and running." 
+# TODO: log success
