add staging deploy script

diff --git a/cloud/deploys/staging_azure/deploy b/cloud/deploys/staging_azure/deploy
--- a/cloud/deploys/staging_azure/deploy
+++ b/cloud/deploys/staging_azure/deploy
@@ -1,40 +1,44 @@
 #! /usr/bin/env bash
 
-set -e
+source "cloud/shared/bin/lib/health.sh"
+source "cloud/azure/bin/lib.sh"
 
-readonly THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE}")")"
-readonly PROJECT_BASE_DIR="$(realpath "${THIS_DIR}/../../../")"
+readonly TF_VAR_FILE="cloud/deploys/staging_azure/staging.tfvars"
+readonly TEMPLATE_DIR="cloud/azure/templates/azure_saml_ses"
+readonly VARS_FILENAME="cloud/deploys/staging_azure/staging_azure_backend_vars"
 
-KEEP_ORIGINAL_PWD=true source "${PROJECT_BASE_DIR}/bin/lib.sh"
-source "${PROJECT_BASE_DIR}/cloud/shared/bin/lib.sh"
-source "${PROJECT_BASE_DIR}/cloud/azure/bin/lib.sh"
-
-readonly TF_VAR_FILE="${THIS_DIR}/staging.tfvars"
-readonly TEMPLATE_DIR="${PROJECT_BASE_DIR}/cloud/azure/templates/azure_saml_ses"
-readonly VARS_FILENAME="${THIS_DIR}/staging_azure_backend_vars"
-
-
+# Apply any infra changes with terraform. This will unset the slot settings, so we'll
+# set them again after we run terraform apply
 terraform \
   -chdir="${TEMPLATE_DIR}" \
   init \
   -backend-config="${VARS_FILENAME}"
 
-# TODO: Make sure the vars required for the commands below are set.
-readonly APP_NAME="$(azure::get_app_name "${RESOURCE_GROUP}")"
-readonly CANARY_URL="$(azure::get_canary_url "${RESOURCE_GROUP}" "${APP_NAME}")"
-
-azure::set_new_container_tag ${RESOURCE_GROUP} ${APP_NAME} ${CONTAINER_TAG}
-
-if health::wait_for_success "${CANARY_URL}"; 
-then
-    echo "New container successfully started in canary slot"
-else
-    # TODO: log failure
-    exit 1
-fi
-
-# There should be at least one Terraform change to swap the slots
 terraform \
   -chdir="${TEMPLATE_DIR}" \
   apply \
   -var-file="${TF_VAR_FILE}"
+
+readonly APP_NAME="$(azure::get_app_name "${AZURE_RESOURCE_GROUP}")"
+readonly CANARY_URL="$(azure::get_canary_url "${AZURE_RESOURCE_GROUP}" "${APP_NAME}")"
+
+azure::set_new_container_tag ${AZURE_RESOURCE_GROUP} ${APP_NAME} ${DOCKER_TAG}
+
+if health::wait_for_success "${CANARY_URL}/loginForm"; 
+then
+    echo "New container successfully started in canary slot"
+else
+    # TODO: log failure + exit early. don't do the swap
+    exit 1
+fi
+
+echo "Swapping deployment slot 'canary' into production. This may take up to 10 minutes."
+azure::swap_deployment_slot "${AZURE_RESOURCE_GROUP}" "${APP_NAME}"
+
+cloud/deploys/dev_azure/configure-slot-settings -g "${AZURE_RESOURCE_GROUP}" "${STAGING_HOSTNAME}"
+
+echo "Success! The new application version is up and running." 
+# TODO: log success
+
+
+
