Adding process check and error message + exit codes

diff --git a/formatter/fmt b/formatter/fmt
--- a/formatter/fmt
+++ b/formatter/fmt
@@ -58,6 +58,12 @@ if [[ -z $(get_modified_java_files) ]]; then
 else
   echo 'Start format java'
   java -jar /fmt.jar --replace $(get_modified_java_files)
+
+  if [[ $? != 0 ]]; then
+    printf "Java formatter failed. Tried formatting these files: %s" "$(get_modified_java_files)"
+    exit 1
+  fi
+
   echo 'Done formatting java'
 fi
 
@@ -82,6 +88,12 @@ else
     --ignore-path ../.prettierignore \
     --ignore-unknown \
     -- $(printf "%s" "${prettier_file_list[@]}")
+
+  if [[ $? != 0 ]]; then
+    printf "Prettier failed. Tried formatting these files: %s" "${prettier_file_list[@]}"
+    exit 1
+  fi
+
   cd ..
   echo 'Done formatting with prettier'
 
