trying out what the snapshot tag is

diff --git a/.github/workflows/azure-saml-ses-deploy-test.yaml b/.github/workflows/azure-saml-ses-deploy-test.yaml
--- a/.github/workflows/azure-saml-ses-deploy-test.yaml
+++ b/.github/workflows/azure-saml-ses-deploy-test.yaml
@@ -33,4 +33,12 @@ jobs:
         run: |
           source civiform_config.sh
           export CIVIFORM_MODE="test"
+          echo "${LATEST_SNAPSHOT_TAG}"
           cloud/azure/bin/deploy "--tag=${LATEST_SNAPSHOT_TAG}"
+          if $?; then
+            echo "Terraform plan succeede"
+            exit 0
+          else
+            echo "Terraform plan failed"
+            exit 1
+          fi
